# Generated by Django 2.0.6 on 2018-06-03 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Novo',
            new_name='Novo_Usuario',
        ),
    ]
